FROM node:lts-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:lts-alpine
WORKDIR /app
COPY --from=builder /app ./
RUN npm install

ENV NODE_ENV=production
EXPOSE 3000
CMD ["node", "./.output/server/index.mjs"]