<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260630073310 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Paiement des licences HelloAsso : tables license + payment et colonne member.status';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE license (season VARCHAR(9) NOT NULL, status VARCHAR(20) NOT NULL, amount INT DEFAULT NULL, hello_asso_tier_id INT DEFAULT NULL, access_token VARCHAR(64) DEFAULT NULL, token_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, medical_certificate_file_name VARCHAR(255) DEFAULT NULL, license_number VARCHAR(50) DEFAULT NULL, approved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, rejection_reason TEXT DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, member_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5768F419B6A2DD68 ON license (access_token)');
        $this->addSql('CREATE INDEX IDX_5768F4197597D3FE ON license (member_id)');
        $this->addSql('CREATE TABLE payment (amount INT NOT NULL, state VARCHAR(20) NOT NULL, hello_asso_checkout_intent_id INT DEFAULT NULL, hello_asso_order_id INT DEFAULT NULL, hello_asso_payment_id INT DEFAULT NULL, payment_receipt_url VARCHAR(1024) DEFAULT NULL, raw_payload JSON NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, license_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6D28840DBCCE7DDB ON payment (hello_asso_payment_id)');
        $this->addSql('CREATE INDEX IDX_6D28840D460F904B ON payment (license_id)');
        $this->addSql('ALTER TABLE license ADD CONSTRAINT FK_5768F4197597D3FE FOREIGN KEY (member_id) REFERENCES member (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D460F904B FOREIGN KEY (license_id) REFERENCES license (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE member ADD status VARCHAR(20) DEFAULT \'active\' NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE license DROP CONSTRAINT FK_5768F4197597D3FE');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840D460F904B');
        $this->addSql('DROP TABLE license');
        $this->addSql('DROP TABLE payment');
        $this->addSql('ALTER TABLE member DROP status');
    }
}
