<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Table `inscription_draft` : brouillon d'inscription publique (champs saisis +
 * pièces déjà déposées) identifié par un token, avant que la demande de licence
 * n'existe.
 *
 * Permet de reprendre une inscription après une déconnexion, et surtout de
 * recevoir les pièces au moment où elles sont choisies — jusqu'ici elles ne
 * partaient qu'après la validation, et un échec pendant cette rafale laissait
 * une demande sans ses pièces.
 *
 * `payload` et `documents` sont en JSON : le formulaire évolue sans migration,
 * et les métadonnées d'un fichier (nom d'origine, mimetype, taille) n'ont pas
 * de vie propre hors du brouillon. Aucune contrainte vers `member`/`license` :
 * un brouillon existe justement avant eux, et disparaît quand ils naissent.
 */
final class Version20260909073543 extends AbstractMigration
{
    public function getDescription(): string
    {
        return "Crée la table inscription_draft (brouillon d'inscription repris par token)";
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE inscription_draft (token VARCHAR(64) NOT NULL, payload JSON NOT NULL, documents JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_inscription_draft_updated_at ON inscription_draft (updated_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_inscription_draft_token ON inscription_draft (token)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE inscription_draft');
    }
}
