<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Table `log` : logs applicatifs persistés par le DoctrineHandler (Monolog),
 * consultables depuis la page d'administration (SUPER_ADMIN).
 */
final class Version20260715074231 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Table log (logs applicatifs persistés par Monolog)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE log (level VARCHAR(20) NOT NULL, channel VARCHAR(50) NOT NULL, message TEXT NOT NULL, context TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_log_created_at ON log (created_at)');
        $this->addSql('CREATE INDEX idx_log_level ON log (level)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE log');
    }
}
