<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260709092237 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE member_document (uuid VARCHAR(36) NOT NULL, type VARCHAR(20) NOT NULL, name VARCHAR(255) NOT NULL, season VARCHAR(9) DEFAULT NULL, system_key VARCHAR(50) DEFAULT NULL, protected BOOLEAN DEFAULT false NOT NULL, stored_name VARCHAR(255) DEFAULT NULL, original_name VARCHAR(255) DEFAULT NULL, mime_type VARCHAR(100) DEFAULT NULL, size INT DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, member_id INT NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2FB4299CD17F50A6 ON member_document (uuid)');
        $this->addSql('CREATE INDEX IDX_2FB4299C727ACA70 ON member_document (parent_id)');
        $this->addSql('CREATE INDEX idx_member_document_member ON member_document (member_id)');
        $this->addSql('ALTER TABLE member_document ADD CONSTRAINT FK_2FB4299C7597D3FE FOREIGN KEY (member_id) REFERENCES member (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE member_document ADD CONSTRAINT FK_2FB4299C727ACA70 FOREIGN KEY (parent_id) REFERENCES member_document (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE member_document DROP CONSTRAINT FK_2FB4299C7597D3FE');
        $this->addSql('ALTER TABLE member_document DROP CONSTRAINT FK_2FB4299C727ACA70');
        $this->addSql('DROP TABLE member_document');
    }
}
