<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Table `season` : liste des saisons sportives enregistrées (alimente le
 * sélecteur de saison). Amorcée avec les saisons déjà présentes dans les
 * licences et la saison courante configurée.
 */
final class Version20260715145842 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée la table season et l\'amorce depuis les licences existantes';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE season (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(9) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F0E45BA95E237E06 ON season (name)');

        // Amorçage : saisons distinctes des licences + saison courante réglée.
        $this->addSql("INSERT INTO season (name, created_at, updated_at) SELECT DISTINCT season, NOW(), NOW() FROM license ON CONFLICT (name) DO NOTHING");
        $this->addSql("INSERT INTO season (name, created_at, updated_at) SELECT value, NOW(), NOW() FROM setting WHERE name = 'current_season' ON CONFLICT (name) DO NOTHING");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE season');
    }
}
