<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260310105011 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_user (email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, member_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E97597D3FE ON app_user (member_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON app_user (email)');
        $this->addSql('CREATE TABLE contact_message (first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, subject VARCHAR(255) NOT NULL, message TEXT NOT NULL, is_read BOOLEAN NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, read_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2C9211FEF5675CD0 ON contact_message (read_by_id)');
        $this->addSql('CREATE TABLE game (opponent VARCHAR(255) NOT NULL, date DATE NOT NULL, meeting_time VARCHAR(10) DEFAULT NULL, venue VARCHAR(10) NOT NULL, location VARCHAR(255) DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, team_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_232B318C296CD8AE ON game (team_id)');
        $this->addSql('CREATE TABLE member (first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, color VARCHAR(7) NOT NULL, phone_number VARCHAR(30) NOT NULL, email VARCHAR(255) NOT NULL, license_paid BOOLEAN DEFAULT false NOT NULL, license_file_name VARCHAR(255) DEFAULT NULL, profile_picture VARCHAR(255) DEFAULT NULL, license_number VARCHAR(50) DEFAULT NULL, gender VARCHAR(10) NOT NULL, birth_date DATE NOT NULL, nationality VARCHAR(100) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, address_street VARCHAR(255) NOT NULL, address_zip VARCHAR(10) NOT NULL, address_city VARCHAR(100) NOT NULL, team_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_70E4FA78296CD8AE ON member (team_id)');
        $this->addSql('CREATE TABLE team (name VARCHAR(255) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE app_user ADD CONSTRAINT FK_88BDF3E97597D3FE FOREIGN KEY (member_id) REFERENCES member (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contact_message ADD CONSTRAINT FK_2C9211FEF5675CD0 FOREIGN KEY (read_by_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game ADD CONSTRAINT FK_232B318C296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE member ADD CONSTRAINT FK_70E4FA78296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE app_user DROP CONSTRAINT FK_88BDF3E97597D3FE');
        $this->addSql('ALTER TABLE contact_message DROP CONSTRAINT FK_2C9211FEF5675CD0');
        $this->addSql('ALTER TABLE game DROP CONSTRAINT FK_232B318C296CD8AE');
        $this->addSql('ALTER TABLE member DROP CONSTRAINT FK_70E4FA78296CD8AE');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE contact_message');
        $this->addSql('DROP TABLE game');
        $this->addSql('DROP TABLE member');
        $this->addSql('DROP TABLE team');
    }
}
