<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260613100058 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'game_history : journal append-only des transactions (create/update/delete) sur les matchs';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE game_history (action VARCHAR(10) NOT NULL, game_id INT DEFAULT NULL, opponent VARCHAR(255) NOT NULL, game_date DATE NOT NULL, team_id INT DEFAULT NULL, team_name VARCHAR(255) NOT NULL, changes JSON NOT NULL, actor_email VARCHAR(180) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_game_history_game_id ON game_history (game_id)');
        $this->addSql('CREATE INDEX idx_game_history_team_id ON game_history (team_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE game_history');
    }
}
