name: CI PROD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      namespace: clapier-admin-prod
      tag-prefix: stable
      api-base: https://clapiersvb.fr/api
    secrets: inherit
