name: CI PREPROD

on:
  push:
    branches: [ preprod ]

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      namespace: clapier-admin-preprod
      tag-prefix: preprod
      api-base: https://preprod.clapiersvb.fr/api
    secrets: inherit
